services:
  - type: web
    name: sms-spam-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/app.py"
    workingDir: backend
    autoDeploy: true

  - type: web
    name: sms-spam-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: frontend/build
    workingDir: frontend
    autoDeploy: true
