[phases.setup]
nixPkgs = ["nodejs", "python39"]

[phases.install]
cmds = [
    "cd frontend && npm ci",
    "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "cp -r frontend/build backend/"
]

[phases.start]
cmd = "cd backend && python app.py"

[variables]
PORT = "8080"